"use client";

import Link from 'next/link';
import { ArrowRightLeft, CheckCircle2, Play, Square } from 'lucide-react';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/Button';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';

const duration = (seconds: number) => {
  const value = Math.max(0, seconds);
  const pad = (part: number) => String(part).padStart(2, '0');
  return `${pad(Math.floor(value / 3600))}:${pad(Math.floor((value % 3600) / 60))}:${pad(value % 60)}`;
};

export function OrderTimerConsole(props: any) {
  const { selectedPart, selectedPartId, selectedPartElapsedSeconds, activeOnSelected, activeElsewhereEntry, otherTimerBadgeLabel, hasActiveEntry, selectedPartActiveTimers, nowMs, selectedCurrentDepartment, selectedTimerWorkerId, timerWorkerOptions, timerSaving, selectedPartCurrentDepartmentId, canStartSelectedPartTimer, canSubmitCurrentDepartment, departmentSubmitBlocker, submitDestinationOptions, canMarkPartComplete, timerReadOnlyMessage, timerError, showTimerDetails, canUseTimerControls, startHelperLabel, kioskHelperLabel, kioskSession, selectedPartStoredSeconds, selectedPartTimerSeconds, selectedPartManualSeconds, partManualAdjustments, selectedPartDepartmentHistory, lastPartEvent, onOpenActiveTimer, onTimerWorkerChange, onStartTimer, onSubmitDepartment, onMoveDepartment, onCompletePart, onToggleDetails } = props;
  return <div className="order-detail-tile space-y-3 rounded-lg border p-3 sm:p-4">
    <div className="flex flex-wrap items-center justify-between gap-3"><div className="space-y-1"><div className="text-xs uppercase tracking-wide text-muted-foreground">Part Controls</div><div className="text-sm font-medium text-foreground">{selectedPart?.partNumber || 'No part selected'}</div><div className="text-xs text-muted-foreground">{selectedPartId ? `Elapsed ${duration(selectedPartElapsedSeconds)}` : 'Pick a part from the left to start work.'}</div></div>{activeOnSelected ? <Badge className="bg-emerald-500/15 text-emerald-200">Running</Badge> : activeElsewhereEntry?.href ? <Button asChild size="sm" variant="ghost" className="h-7 bg-emerald-500/15 px-2 text-emerald-200 hover:bg-emerald-500/25 hover:text-emerald-100"><Link href={activeElsewhereEntry.href}>{otherTimerBadgeLabel}</Link></Button> : <Badge className={hasActiveEntry ? 'bg-emerald-500/15 text-emerald-200' : 'bg-muted text-foreground'}>{hasActiveEntry ? otherTimerBadgeLabel : 'Idle'}</Badge>}</div>
    {selectedPartId ? <div className="order-detail-inset rounded-md border p-3"><div className="flex flex-wrap items-center gap-2 text-xs text-muted-foreground"><span className="font-medium text-foreground">Active timers:</span>{selectedPartActiveTimers.length ? selectedPartActiveTimers.map((entry: any) => { const workerName=entry?.user?.name?.trim()||entry?.user?.email?.trim()||entry?.userId||'Worker'; const departmentName=entry?.departmentName?.trim()||entry?.departmentId?.trim()||'Unknown dept'; const started=new Date(entry?.startedAt).getTime(); const elapsed=Number.isFinite(started)?Math.max(0,Math.floor((nowMs-started)/1000)):0; return <Button key={entry?.id ?? `${entry?.userId}-${entry?.departmentId}`} type="button" size="sm" variant="outline" className="h-8 border-emerald-500/30 bg-emerald-500/10 px-2 text-[11px] text-emerald-100 hover:bg-emerald-500/20 hover:text-emerald-50" onClick={() => onOpenActiveTimer(entry)}><span>{workerName}, {departmentName}, {duration(elapsed)}</span><Square className="ml-2 h-3.5 w-3.5 opacity-80" /></Button>; }) : <span>No active timers on this part.</span>}</div>{selectedPartActiveTimers.length ? <div className="mt-2 text-[11px] text-muted-foreground">Click a timer to pause or finish it from this console.</div> : null}</div> : null}
    <div className="grid gap-2 md:grid-cols-2"><div className="flex h-10 items-center rounded-md border border-border/60 bg-background/80 px-3 text-sm"><span className="text-muted-foreground">Department:&nbsp;</span><span className="font-medium text-foreground">{selectedCurrentDepartment?.name ?? 'Assign a department first'}</span></div><Select value={selectedTimerWorkerId || '__none__'} onValueChange={(value) => onTimerWorkerChange(value === '__none__' ? '' : value)}><SelectTrigger className="h-10 border-border/60 bg-background/80"><SelectValue placeholder="Select employee" /></SelectTrigger><SelectContent><SelectItem value="__none__">Select employee</SelectItem>{timerWorkerOptions.map((user: any) => <SelectItem key={user.id} value={user.id}>{user.name}</SelectItem>)}</SelectContent></Select></div>
    <div className="grid gap-2 lg:grid-cols-2 xl:grid-cols-4"><Button type="button" size="sm" disabled={!selectedPartId||timerSaving||!selectedPartCurrentDepartmentId||!selectedTimerWorkerId||!canStartSelectedPartTimer} onClick={onStartTimer} className="justify-center gap-2"><Play className="h-4 w-4" />Start employee timer</Button><Button type="button" size="sm" variant="outline" disabled={!selectedPartId||timerSaving||!canSubmitCurrentDepartment} onClick={onSubmitDepartment} className="justify-center gap-2" title={departmentSubmitBlocker??undefined}><CheckCircle2 className="h-4 w-4" />Submit {selectedCurrentDepartment?.name??'department'} complete</Button><Button type="button" size="sm" variant="outline" disabled={!selectedPartId||timerSaving||submitDestinationOptions.length===0} onClick={onMoveDepartment} className="justify-center gap-2"><ArrowRightLeft className="h-4 w-4" />{selectedPartCurrentDepartmentId?'Move department':'Assign department'}</Button><Button type="button" size="sm" variant="outline" disabled={!selectedPartId||timerSaving||!canMarkPartComplete} onClick={onCompletePart} className="justify-center gap-2"><CheckCircle2 className="h-4 w-4" /><span>Mark Shipped</span></Button></div>
    {selectedPartCurrentDepartmentId&&departmentSubmitBlocker?<div className="rounded-md border border-amber-500/30 bg-amber-500/10 px-3 py-2 text-xs text-amber-100"><span className="font-medium">Department completion unavailable:</span> {departmentSubmitBlocker}</div>:null}
    <div className="flex flex-wrap items-center justify-between gap-3 text-xs text-muted-foreground"><span>{timerReadOnlyMessage}</span><Button type="button" size="sm" variant="ghost" onClick={onToggleDetails} className="h-7 px-2 text-xs">{showTimerDetails?'Hide details':'Show details'}</Button></div>
    {timerError?<div className="rounded-md border border-destructive/40 bg-destructive/10 px-3 py-2 text-xs text-destructive">{timerError}</div>:null}
    {showTimerDetails?<><div className="order-detail-inset flex flex-wrap items-center justify-between gap-3 rounded-md border p-3 text-xs text-slate-300"><div className="flex items-start gap-2"><ArrowRightLeft className="mt-0.5 h-3.5 w-3.5" /><span>{canUseTimerControls?startHelperLabel:kioskHelperLabel}</span></div>{!canUseTimerControls?<span className="font-medium text-foreground">{kioskSession?`${kioskSession.worker?.name||kioskSession.worker?.email||'Kiosk user'} unlocked`:'PIN required for kiosk timing'}</span>:null}</div>{selectedPartId?<div className="order-detail-inset rounded-md border px-3 py-2 text-xs text-slate-300"><div><span className="font-medium text-foreground">Total time:</span> {duration(selectedPartStoredSeconds)}</div><div>Timer time: {duration(selectedPartTimerSeconds)}</div><div>Manual added time: {duration(selectedPartManualSeconds)}</div>{partManualAdjustments.length?<div className="mt-2 space-y-1">{partManualAdjustments.map((entry:any)=><div key={entry.id}>+{duration(Number(entry.seconds??0))} — {entry.note}</div>)}</div>:null}{selectedPartDepartmentHistory.length?<div className="mt-3 space-y-2"><div className="grid gap-2 md:grid-cols-2">{selectedPartDepartmentHistory.map((group:any)=><div key={group.departmentId??'__none__'} className="order-detail-inset rounded border p-2"><div className="text-[11px] text-muted-foreground">{group.departmentName}</div><div className="text-sm font-semibold text-foreground">{duration(group.totalSeconds)}</div></div>)}</div><div className="space-y-1">{selectedPartDepartmentHistory.map((group:any)=><div key={`${group.departmentId??'__none__'}_rows`} className="order-detail-inset rounded border p-2"><div className="mb-1 text-[11px] font-medium text-foreground">{group.departmentName}</div>{group.entries.slice(0,3).map((entry:any)=><div key={entry.id} className="flex items-center justify-between gap-2 text-[11px] text-muted-foreground"><span>{new Date(entry.startedAt).toLocaleString()}</span><span className="font-medium text-foreground">{duration(entry.durationSeconds)}</span></div>)}</div>)}</div></div>:null}</div>:null}<div className="text-xs text-muted-foreground">{lastPartEvent?<span>Last action: <span className="font-medium text-foreground">{lastPartEvent.message}</span> · {new Date(lastPartEvent.createdAt).toLocaleString()}</span>:<span>Last action: none yet for this part.</span>}</div></>:null}
  </div>;
}
