'use client';

import { Button } from '@/components/ui/Button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/Card';
import { Input } from '@/components/ui/Input';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Textarea } from '@/components/ui/Textarea';
import { calculateProcurementTotalCents } from '@/modules/pricing/part-pricing';

type Vendor = { id: string; name: string };
type Part = { key: string; name: string; partNumber: string; materialStatus: string; procurementVendorId: string; procurementCost: string; procurementMarkupPercent: string };
type Item = { key: string; vendorId: string; vendorName: string; partNumber: string; partUrl: string; basePrice: string; markupPercent: string; notes: string };
type Props = { parts: Part[]; vendors: Vendor[]; items: Item[]; onPartChange: (key: string, patch: Partial<Part>) => void; onItemChange: (key: string, patch: Partial<Item>) => void; onRemoveItem: (key: string) => void; onAddItem: () => void };
const cents = (value: string) => {
  const parsed = Number.parseFloat(value || '0');
  return Number.isNaN(parsed) || parsed < 0 ? 0 : Math.round(parsed * 100);
};
const money = (value: number) => new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format((value || 0) / 100);

export function QuotePurchasedItemsCard({ parts, vendors, items, onPartChange, onItemChange, onRemoveItem, onAddItem }: Props) {
  const purchaseParts = parts.filter((part) => part.name.trim() && part.materialStatus === 'NEED_TO_ORDER');
  return <Card><CardHeader><CardTitle>Purchased items</CardTitle><CardDescription>Costs stay attached to the part that needs them. Vendors selected during material check are carried forward automatically.</CardDescription></CardHeader><CardContent className="space-y-4">
    {purchaseParts.map((part) => { const vendorName=vendors.find((vendor)=>vendor.id===part.procurementVendorId)?.name||'Vendor not selected'; const total=calculateProcurementTotalCents({baseCostCents:cents(part.procurementCost),markupPercent:Number.parseFloat(part.procurementMarkupPercent||'0')||0}); const resolved=Boolean(part.procurementVendorId)&&part.procurementCost.trim().length>0; return <div key={part.key} className={`rounded border p-4 ${resolved?'border-[#0b1f3a] bg-[#0b1f3a]/20':'border-[#ff5a00]/60 bg-[#ff5a00]/5'}`}><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-sm font-semibold">{part.partNumber||part.name}</p><p className="text-xs text-muted-foreground">{part.name} · Vendor: {vendorName}</p></div><span className={`rounded-full border px-2 py-1 text-xs font-semibold ${resolved?'border-primary/50 bg-primary/15 text-primary':'border-[#ff5a00]/60 bg-[#ff5a00]/10 text-[#ff8a4c]'}`}>{resolved?'Cost captured':'Enter cost'}</span></div><div className="mt-3 grid gap-3 sm:grid-cols-[1fr_140px_auto] sm:items-end"><div className="grid gap-2"><Label>Material cost (USD)</Label><Input type="number" min="0" step="0.01" value={part.procurementCost} onChange={(event)=>onPartChange(part.key,{procurementCost:event.target.value})} placeholder="0.00" /></div><div className="grid gap-2"><Label>Markup %</Label><Input type="number" min="0" step="1" value={part.procurementMarkupPercent} onChange={(event)=>onPartChange(part.key,{procurementMarkupPercent:event.target.value})} /></div><div className="rounded border border-border/60 bg-card p-3 text-sm"><span className="text-muted-foreground">Quoted total</span><p className="font-semibold text-primary">{money(total)}</p></div></div><p className={`mt-3 text-xs ${resolved?'text-muted-foreground':'text-[#ff8a4c]'}`}>{resolved?"This purchase is included in this part's calculated price below.":'Enter the material cost to finish pricing this part.'}</p></div>; })}
    {!purchaseParts.length?<div className="rounded border border-dashed border-border/60 bg-background/40 p-3 text-sm text-muted-foreground">No part-specific purchased material has been marked for ordering.</div>:null}
    {items.map((item)=>{const total=Math.round(cents(item.basePrice)*(1+(Number.parseFloat(item.markupPercent||'0')||0)/100)); return <div key={item.key} className="rounded border border-border/50 bg-card/40 p-4"><div className="grid gap-4 md:grid-cols-2"><div className="grid gap-2"><Label>Vendor</Label><Select value={item.vendorId} onValueChange={(value)=>onItemChange(item.key,{vendorId:value,vendorName:vendors.find((vendor)=>vendor.id===value)?.name??''})}><SelectTrigger className="border border-border bg-background px-3 py-2 text-sm"><SelectValue placeholder="Select vendor" /></SelectTrigger><SelectContent>{vendors.map((vendor)=><SelectItem key={vendor.id} value={vendor.id}>{vendor.name}</SelectItem>)}</SelectContent></Select></div><div className="grid gap-2"><Label>Override vendor name</Label><Input value={item.vendorName} onChange={(event)=>onItemChange(item.key,{vendorName:event.target.value})} placeholder={vendors.find((vendor)=>vendor.id===item.vendorId)?.name} /></div><div className="grid gap-2"><Label>Part number</Label><Input value={item.partNumber} onChange={(event)=>onItemChange(item.key,{partNumber:event.target.value})} /></div><div className="grid gap-2"><Label>Link</Label><Input value={item.partUrl} onChange={(event)=>onItemChange(item.key,{partUrl:event.target.value})} placeholder="https://" /></div><div className="grid gap-2"><Label>Base cost (USD)</Label><Input type="number" step="0.01" min="0" value={item.basePrice} onChange={(event)=>onItemChange(item.key,{basePrice:event.target.value})} /></div><div className="grid gap-2"><Label>Markup %</Label><div className="flex flex-wrap items-center gap-2"><Input className="w-24" type="number" step="1" value={item.markupPercent} onChange={(event)=>onItemChange(item.key,{markupPercent:event.target.value})} /><span className="text-xs text-muted-foreground">Suggestions:</span>{[10,15,20].map((suggestion)=><Button key={suggestion} type="button" variant="outline" size="sm" className="h-7 px-2 text-xs" onClick={()=>onItemChange(item.key,{markupPercent:String(suggestion)})}>{suggestion}%</Button>)}</div></div></div><div className="mt-4 flex items-center justify-between"><div className="text-sm text-muted-foreground">Estimated total: <span className="font-medium text-primary">{money(total)}</span></div><Button type="button" variant="ghost" onClick={()=>onRemoveItem(item.key)}>Remove</Button></div><div className="mt-4 grid gap-2"><Label>Notes</Label><Textarea value={item.notes} onChange={(event)=>onItemChange(item.key,{notes:event.target.value})} placeholder="Why is this item required?" /></div></div>;})}
    <Button type="button" variant="outline" onClick={onAddItem}>Add purchased item</Button>
  </CardContent></Card>;
}
